cmake_minimum_required(VERSION 3.1)
include(${CMAKE_CURRENT_LIST_DIR}/GlobalConfiguration.txt)
include(${CMAKE_CURRENT_LIST_DIR}/Operations.txt)
include(${CMAKE_CURRENT_LIST_DIR}/Logging.txt)
include(${CMAKE_CURRENT_LIST_DIR}/ProjectMacros.txt)
include(${CMAKE_CURRENT_LIST_DIR}/ThirdPartyMacros.txt)
