cmake_minimum_required(VERSION 3.1)
include(${CMAKE_CURRENT_LIST_DIR}/GlobalConfiguration.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Operations.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Logging.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/FileMacros.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ProjectMacros.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/ThirdPartyMacros.cmake)
